{% set name = "pantable" %}
{% set version = "0.13.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 264a9895b06fc609ec3e0de034a806466df1088d6200db85ced5386b365ee64c

build:
  noarch: python
  number: 0
  entry_points:
    - pantable = pantable.cli.pantable:main
    - pantable2csv = pantable.cli.pantable2csv:main
    - pantable2csvx = pantable.cli.pantable2csvx:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry >=1,<2
  run:
    - backports.cached-property >=1,<2  # remove this when dropping py37
    - numpy >=1,<2
    - panflute >=2,<3
    - python >=3.7
    - pyyaml >=5,<6
  run_constrained:
    - pandoc >=2.11.2,<2.12
    - coloredlogs >=14,<16
    - tabulate >=0.8,<0.9
    - yamlloader >=0.5,<0.6

test:
  imports:
    - pantable
    - pantable.cli
  commands:
    - pip check
    - |
      echo '# testing' | pandoc -F pantable
      echo '# testing' | pandoc -F pantable2csv
      echo '# testing' | pandoc -F pantable2csvx
  requires:
    - pip

about:
  home: https://github.com/ickc/pantable
  summary: A Python library for writing pandoc filters for tables with batteries included.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library. Pandoc filters is a UNIX filter that intercept the pandoc AST and modify document. Pantable is a pandoc filter that process tables in the AST.
  doc_url: https://ickc.github.io/pantable/
  dev_url: https://github.com/ickc/pantable/

extra:
  recipe-maintainers:
    - ickc
